services:
  frontend:
    build: .
    container_name: hackhub-frontend
    ports:
      - "80:80"
    networks:
      - hackhub-network

networks:
  hackhub-network:
    external: true
    name: hackhub-shared-net # Deve corrispondere al nome nel file del backend
