services:
  db:
    image: postgres:15-alpine
    container_name: hackhub-db
    environment:
      - POSTGRES_DB=hackhub_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hackhub-network

  backend:
    build: .
    container_name: hackhub-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hackhub_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      # Forza il dialetto PostgreSQL per evitare l'errore createClob() di H2
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      # Disabilita il check dei metadati che causa il crash del driver Postgres
      - SPRING_JPA_PROPERTIES_HIBERNATE_TEMP_USE_JDBC_METADATA_DEFAULTS=false
      - JWT_SECRET=xz41wVXiG3IZq2a461ZBfdECYHXtHk+ffsZpvP7wWEY=
    depends_on:
      - db
    networks:
      - hackhub-network

networks:
  hackhub-network:
    name: hackhub-shared-net
    driver: bridge

volumes:
  postgres_data: