on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 1. Rendi lo script eseguibile (fondamentale su GitHub Actions)
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: ./hackHub

      # 2. Esegui i test entrando nella cartella hackHub
      - name: Run Tests with Gradle
        run: ./gradlew test
        working-directory: ./hackHub

      # 3. Compila il JAR entrando nella cartella hackHub
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./hackHub

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Build e Push: il context deve puntare alla cartella dove c'Ã¨ il Dockerfile
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./hackHub   # <--- Importante: entra qui per trovare Dockerfile e JAR
          push: true
          tags: lorenzosarti22/hackhub-backend:latest